### ISSUE TITLE
出现too many indices for tensor of dimension 1，请问这个问题该怎么解决呢

### ISSUE THREAD

**Issue by zzc-ai** [Sharpiless/Yolov5-deepsort-inference#1]
![image](https://user-images.githubusercontent.com/63056505/103506991-0ec9c880-4e99-11eb-85d9-b27681e6c1fb.png)

**Comment by Sharpiless** [comment]
这个是因为检测到的目标数目为0，导致索引出错，只需要加一下判断目标数即可

**Comment by zzc-ai** [comment]
在运行初期已经出现了fps是10了，目标数是0的话，那我加的判断条件应该是什么呢？
if COUNT == 0:
break
这样吗，如果能解答就太感谢了，耽误您时间了，抱歉

**Comment by Sharpiless** [comment]
新版本已经修复了这个bug，重新clone一下即可
