### ISSUE TITLE
能否在网页端实时检测

### ISSUE THREAD

**Issue by ash-ali** [Sharpiless/Yolov5-deepsort-inference#4]
能否在网页端实时检测，或者检测视频

**Comment by Sharpiless** [comment]
应该可以用TorchServe做，但是我没有相关经验

**Comment by Sharpiless** [comment]
我新建了一个仓库，用Flask+VUE实现了WEB端部署，可以看一下：
https://github.com/Sharpiless/Yolov5-Flask-VUE
